//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booze.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Booze.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to your location?.
        /// </summary>
        public static string Ajustes_Permissao {
            get {
                return ResourceManager.GetString("Ajustes_Permissao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation timeout:.
        /// </summary>
        public static string Ajustes_Timeout {
            get {
                return ResourceManager.GetString("Ajustes_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        public static string Ajustes_Timeout_10 {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 seconds.
        /// </summary>
        public static string Ajustes_Timeout_30 {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option sets the maximum time the GPS has to get your position. After this period, the best location that could be acquired is returned.
        ///
        ///The longer the timeout set, the more accurate the result tends to be..
        /// </summary>
        public static string Ajustes_Timeout_Message {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Ajustes_Timeout_None {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (tap for details).
        /// </summary>
        public static string Ajustes_Timeout_Subtle {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_Subtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geolocation timeout.
        /// </summary>
        public static string Ajustes_Timeout_Title {
            get {
                return ResourceManager.GetString("Ajustes_Timeout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Ajustes_Title {
            get {
                return ResourceManager.GetString("Ajustes_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Booze!
        ///
        ///Would you like to rate and review the app in the Windows Store?.
        /// </summary>
        public static string App_Review_Message {
            get {
                return ResourceManager.GetString("App_Review_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate/review the app.
        /// </summary>
        public static string App_Review_Title {
            get {
                return ResourceManager.GetString("App_Review_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No place found in this search range..
        /// </summary>
        public static string Busca_NoPlace {
            get {
                return ResourceManager.GetString("Busca_NoPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string ContextMenu_Remover {
            get {
                return ResourceManager.GetString("ContextMenu_Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: .
        /// </summary>
        public static string Detalhes_Bairro {
            get {
                return ResourceManager.GetString("Detalhes_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: .
        /// </summary>
        public static string Detalhes_Endereco {
            get {
                return ResourceManager.GetString("Detalhes_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to favorites..
        /// </summary>
        public static string Detalhes_Favoritos_Add {
            get {
                return ResourceManager.GetString("Detalhes_Favoritos_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from favorites..
        /// </summary>
        public static string Detalhes_Favoritos_Rem {
            get {
                return ResourceManager.GetString("Detalhes_Favoritos_Rem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening hours.
        /// </summary>
        public static string Detalhes_Horarios {
            get {
                return ResourceManager.GetString("Detalhes_Horarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No number..
        /// </summary>
        public static string Detalhes_Ligar_NA {
            get {
                return ResourceManager.GetString("Detalhes_Ligar_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers:.
        /// </summary>
        public static string Detalhes_Ligar_Numeros {
            get {
                return ResourceManager.GetString("Detalhes_Ligar_Numeros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DiaSemana_Domingo {
            get {
                return ResourceManager.GetString("DiaSemana_Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DiaSemana_Quarta {
            get {
                return ResourceManager.GetString("DiaSemana_Quarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DiaSemana_Quinta {
            get {
                return ResourceManager.GetString("DiaSemana_Quinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DiaSemana_Sabado {
            get {
                return ResourceManager.GetString("DiaSemana_Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DiaSemana_Segunda {
            get {
                return ResourceManager.GetString("DiaSemana_Segunda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DiaSemana_Sexta {
            get {
                return ResourceManager.GetString("DiaSemana_Sexta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DiaSemana_Terca {
            get {
                return ResourceManager.GetString("DiaSemana_Terca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyday.
        /// </summary>
        public static string DiaSemana_TodosDias {
            get {
                return ResourceManager.GetString("DiaSemana_TodosDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        public static string Favoritos_ExcluirLista_Caption {
            get {
                return ResourceManager.GetString("Favoritos_ExcluirLista_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Favoritos_ExcluirLista_Message {
            get {
                return ResourceManager.GetString("Favoritos_ExcluirLista_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favoritos_Null_Caption {
            get {
                return ResourceManager.GetString("Favoritos_Null_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no places added..
        /// </summary>
        public static string Favoritos_Null_Message {
            get {
                return ResourceManager.GetString("Favoritos_Null_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string Favoritos_Title {
            get {
                return ResourceManager.GetString("Favoritos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Hora_As {
            get {
                return ResourceManager.GetString("Hora_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not available).
        /// </summary>
        public static string Horarios_NA {
            get {
                return ResourceManager.GetString("Horarios_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string IconButton_Ajuda {
            get {
                return ResourceManager.GetString("IconButton_Ajuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string IconButton_Concluir {
            get {
                return ResourceManager.GetString("IconButton_Concluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string IconButton_Desfavoritar {
            get {
                return ResourceManager.GetString("IconButton_Desfavoritar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string IconButton_Favoritar {
            get {
                return ResourceManager.GetString("IconButton_Favoritar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string IconButton_Favoritos {
            get {
                return ResourceManager.GetString("IconButton_Favoritos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string IconButton_Ligar {
            get {
                return ResourceManager.GetString("IconButton_Ligar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to navigation.
        /// </summary>
        public static string IconButton_Navegacao {
            get {
                return ResourceManager.GetString("IconButton_Navegacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string IconButton_Submeter {
            get {
                return ResourceManager.GetString("IconButton_Submeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string IconButton_Trajeto {
            get {
                return ResourceManager.GetString("IconButton_Trajeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place: .
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MenuItem_Ajustes {
            get {
                return ResourceManager.GetString("MenuItem_Ajustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change view.
        /// </summary>
        public static string MenuItem_AlternarVista {
            get {
                return ResourceManager.GetString("MenuItem_AlternarVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string MenuItem_Atualizar {
            get {
                return ResourceManager.GetString("MenuItem_Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete all.
        /// </summary>
        public static string MenuItem_ExcluirLista {
            get {
                return ResourceManager.GetString("MenuItem_ExcluirLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report information error.
        /// </summary>
        public static string MenuItem_Relatar {
            get {
                return ResourceManager.GetString("MenuItem_Relatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MenuItem_Sobre {
            get {
                return ResourceManager.GetString("MenuItem_Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Erro_Caption {
            get {
                return ResourceManager.GetString("MessageBox_Erro_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current position could not be obtained.
        ///
        ///Make sure that the location services of your device are enabled..
        /// </summary>
        public static string MessageBox_Erro_Localizacao {
            get {
                return ResourceManager.GetString("MessageBox_Erro_Localizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow access to your location?.
        /// </summary>
        public static string MessageBox_Permissao_Caption {
            get {
                return ResourceManager.GetString("MessageBox_Permissao_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature needs to know your location in order to work.
        ///
        ///The permission can be changed at any time under the /settings/ menu..
        /// </summary>
        public static string MessageBox_Permissao_Message {
            get {
                return ResourceManager.GetString("MessageBox_Permissao_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to areas.
        /// </summary>
        public static string Pivot_Bairros {
            get {
                return ResourceManager.GetString("Pivot_Bairros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string Pivot_Proximos {
            get {
                return ResourceManager.GetString("Pivot_Proximos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string Pivot_Todos {
            get {
                return ResourceManager.GetString("Pivot_Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report information error.
        /// </summary>
        public static string RelatarErro {
            get {
                return ResourceManager.GetString("RelatarErro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic art:.
        /// </summary>
        public static string Sobre_ArteGrafica {
            get {
                return ResourceManager.GetString("Sobre_ArteGrafica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        public static string Sobre_Avaliar {
            get {
                return ResourceManager.GetString("Sobre_Avaliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string Sobre_Compartilhar {
            get {
                return ResourceManager.GetString("Sobre_Compartilhar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out &quot;Booze&quot; for Windows Phone.
        /// </summary>
        public static string Sobre_Compartilhar_Message {
            get {
                return ResourceManager.GetString("Sobre_Compartilhar_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        public static string Sobre_Compartilhar_RedesSociais {
            get {
                return ResourceManager.GetString("Sobre_Compartilhar_RedesSociais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact.
        /// </summary>
        public static string Sobre_Contato {
            get {
                return ResourceManager.GetString("Sobre_Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (insert the subject).
        /// </summary>
        public static string Sobre_Contato_Subject {
            get {
                return ResourceManager.GetString("Sobre_Contato_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer:.
        /// </summary>
        public static string Sobre_Desenvolvedor {
            get {
                return ResourceManager.GetString("Sobre_Desenvolvedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Sobre_PrivacyPolicy_Caption {
            get {
                return ResourceManager.GetString("Sobre_PrivacyPolicy_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://1drv.ms/b/s!AiXBYMBQYdbyb8g_g_UPbUQNcxI.
        /// </summary>
        public static string Sobre_PrivacyPolicy_Link {
            get {
                return ResourceManager.GetString("Sobre_PrivacyPolicy_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report bug.
        /// </summary>
        public static string Sobre_RelatarBug {
            get {
                return ResourceManager.GetString("Sobre_RelatarBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report.
        /// </summary>
        public static string Sobre_RelatarBug_Subject {
            get {
                return ResourceManager.GetString("Sobre_RelatarBug_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Sobre_Versao {
            get {
                return ResourceManager.GetString("Sobre_Versao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place submission.
        /// </summary>
        public static string Submit_Ajuda_Caption {
            get {
                return ResourceManager.GetString("Submit_Ajuda_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is meant to allow users to contribute to the expansion of the application&apos;s database.
        ///
        ///If you know a bar that does not appear in the app and want to see it included, this feature allows you to send us information about it; this data will support its future addition..
        /// </summary>
        public static string Submit_Ajuda_Message {
            get {
                return ResourceManager.GetString("Submit_Ajuda_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area:.
        /// </summary>
        public static string Submit_Bairro {
            get {
                return ResourceManager.GetString("Submit_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string Submit_Categoria {
            get {
                return ResourceManager.GetString("Submit_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place submission.
        /// </summary>
        public static string Submit_Email_Subject {
            get {
                return ResourceManager.GetString("Submit_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m at the bar!.
        /// </summary>
        public static string Submit_EstouNoBar {
            get {
                return ResourceManager.GetString("Submit_EstouNoBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get location.
        /// </summary>
        public static string Submit_GetLocation_Caption {
            get {
                return ResourceManager.GetString("Submit_GetLocation_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your geographic position will be acquired.
        ///
        ///Proceed?.
        /// </summary>
        public static string Submit_GetLocation_Message {
            get {
                return ResourceManager.GetString("Submit_GetLocation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information:.
        /// </summary>
        public static string Submit_InfoAdc {
            get {
                return ResourceManager.GetString("Submit_InfoAdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area: .
        /// </summary>
        public static string Submit_Information_Bairro {
            get {
                return ResourceManager.GetString("Submit_Information_Bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string Submit_Information_Nome {
            get {
                return ResourceManager.GetString("Submit_Information_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place&apos;s name:.
        /// </summary>
        public static string Submit_NomeLocal {
            get {
                return ResourceManager.GetString("Submit_NomeLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit submission.
        /// </summary>
        public static string Submit_NotNull_Caption {
            get {
                return ResourceManager.GetString("Submit_NotNull_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Submit_NotNull_Message {
            get {
                return ResourceManager.GetString("Submit_NotNull_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        public static string Submit_Opcional {
            get {
                return ResourceManager.GetString("Submit_Opcional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the field (required)..
        /// </summary>
        public static string Submit_PreencherCampo {
            get {
                return ResourceManager.GetString("Submit_PreencherCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reacquire location.
        /// </summary>
        public static string Submit_Reacquire_Caption {
            get {
                return ResourceManager.GetString("Submit_Reacquire_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Submit_Reacquire_Message {
            get {
                return ResourceManager.GetString("Submit_Reacquire_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address, opening hours, phone numbers, etc..
        /// </summary>
        public static string Submit_StandardText {
            get {
                return ResourceManager.GetString("Submit_StandardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submission.
        /// </summary>
        public static string Submit_Title {
            get {
                return ResourceManager.GetString("Submit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquiring your position....
        /// </summary>
        public static string SysTray_Localizacao {
            get {
                return ResourceManager.GetString("SysTray_Localizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating route....
        /// </summary>
        public static string SysTray_Trajeto {
            get {
                return ResourceManager.GetString("SysTray_Trajeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string Trajeto_Distancia {
            get {
                return ResourceManager.GetString("Trajeto_Distancia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature needs Internet access to perform the calculation of the route and its waypoints, besides the occasional download of maps.
        ///
        ///Make sure to provide the connection via 3/4G or Wi-Fi and try again..
        /// </summary>
        public static string Trajeto_SemConexao_Msg {
            get {
                return ResourceManager.GetString("Trajeto_SemConexao_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection available.
        /// </summary>
        public static string Trajeto_SemConexao_Title {
            get {
                return ResourceManager.GetString("Trajeto_SemConexao_Title", resourceCulture);
            }
        }
    }
}
